const SAMPLE_RATE = 16000;
const WEBSOCKET_TIMEOUT_MS = 30000;
const TERMINATION_TIMEOUT_MS = 5000;
const TOKEN_REFRESH_BUFFER_MS = 30000;
const TOKEN_EXPIRY_MS = 300000;
const REWARM_DELAY_MS = 2000;
const MAX_REWARM_ATTEMPTS = 10;
const KEEPALIVE_INTERVAL_MS = 15000;
const MAX_STREAMING_BUFFERED_BYTES = 8 * 1024 * 1024;
const MAX_STREAMING_INBOUND_MESSAGE_BYTES = 1024 * 1024;
const MAX_STREAMING_TRANSCRIPT_CHARS = 2 * 1024 * 1024;
const MAX_STREAMING_TURN_CHARS = 200 * 1024;
const MAX_STREAMING_TURNS = 10_000;
const MAX_STREAMING_SESSION_AUDIO_BYTES = 512 * 1024 * 1024;
const MAX_STREAMING_SESSION_MS = 2 * 60 * 60 * 1000;

module.exports = {
  SAMPLE_RATE,
  WEBSOCKET_TIMEOUT_MS,
  TERMINATION_TIMEOUT_MS,
  TOKEN_REFRESH_BUFFER_MS,
  TOKEN_EXPIRY_MS,
  REWARM_DELAY_MS,
  MAX_REWARM_ATTEMPTS,
  KEEPALIVE_INTERVAL_MS,
  MAX_STREAMING_BUFFERED_BYTES,
  MAX_STREAMING_INBOUND_MESSAGE_BYTES,
  MAX_STREAMING_SESSION_AUDIO_BYTES,
  MAX_STREAMING_SESSION_MS,
  MAX_STREAMING_TRANSCRIPT_CHARS,
  MAX_STREAMING_TURN_CHARS,
  MAX_STREAMING_TURNS,
};
