// Synthetic text that preserves the length, repeated-token, and model-repair
// characteristics of the reported incident without storing private dictation.
export const SYNTHETIC_LONG_FORM_MODEL_REPAIR = {
  original:
    "Create this maintenance plan in the sample project, and then write a handoff note and plan for a developer to follow. Ask the developer to use review cycles, frequent checkpoints. At each checkpoint it should use two reviewers dividing up scope as appropriate, and then keep those reviewers available for targeted rechecks until clear, and it should refresh the local preview after each checkpoint, and then do a final verification and publish. Include suitable guardrails in the note to keep to the scope and avoid over engineering. We want a clear, low cognitive load solution that follows the best practice programming principles and technical principles documented in the sample repository, such as the file size policy, and it should read key standards files like the file size policy, logging, testing policies, etc. and keep them in context while it works. It should use explorer and worker helpers and use review cycles on the generated note and plan file until you are satisfied it meets best practice and the stated requirements. Then save the changes to the sample project and open the note in VS Code when the note is ready. Take into account that the developer will run this sample workflow from the project folder for one session.",
  repaired:
    "Create this maintenance plan in the sample project, and then write a handoff note and plan for a developer to follow. Ask the developer to use review cycles and frequent checkpoints. At each checkpoint, it should use two reviewers, dividing up the scope as appropriate, and then keep those reviewers available for targeted rechecks until clear. It should refresh the local preview after each checkpoint, and then do a final verification and publish.\n\nInclude suitable guardrails in the note to keep to the scope and avoid overengineering. We want a clear, low-cognitive-load solution that follows the best-practice programming principles and technical principles documented in the sample repository, such as the file size policy. It should read key standards files, like the file size, logging, and testing policies, and keep them in context while it works.\n\nIt should use explorer and worker helpers and use review cycles on the generated note and plan file until you are satisfied that they meet best practices and the stated requirements. Then save the changes to the sample project and open the note in VS Code when the note is ready. Take into account that the developer will run this sample workflow from the project folder for one session.",
  strict:
    "Create this maintenance plan in the sample project, and then write a handoff note and plan for a developer to follow. Ask the developer to use review cycles, frequent checkpoints. At each checkpoint, it should use two reviewers, dividing up scope as appropriate, and then keep those reviewers available for targeted rechecks until clear. And it should refresh the local preview after each checkpoint, and then do a final verification and publish.\n\nInclude suitable guardrails in the note to keep to the scope and avoid over engineering. We want a clear, low cognitive load solution that follows the best practice programming principles and technical principles documented in the sample repository, such as the file size policy, and it should read key standards files like the file size policy, logging, testing policies, etc., and keep them in context while it works.\n\nIt should use explorer and worker helpers and use review cycles on the generated note and plan file until you are satisfied it meets best practice and the stated requirements. Then save the changes to the sample project and open the note in VS Code when the note is ready. Take into account that the developer will run this sample workflow from the project folder for one session.",
} as const;
